SELECT SYSDATE FROM dual;

-- 본인 이름
-- 박서연

-- 테이블 생성쿼리
CREATE TABLE tbl_student(
	student_id VARCHAR(100),
	student_name VARCHAR(100),
	student_age NUMBER,
	department_id VARCHAR(100),
	ADDRESS_ID VARCHAR(100),
	CONSTRAINTS PK_STUDENT PRIMARY KEY(STUDENT_ID),
	CONSTRAINTS FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES TBL_STUDENT(STUDENT_ID),
	CONSTRAINTS FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES TBL_ADDRESS(ADDRESS_ID)
);

CREATE TABLE TBL_DEPARTMENT(
	DEPARTMENT_ID VARCHAR(100),
	DEPARTMENT_NAME VARCHAR(100) UNIQUE,
	CONSTRAINTS PK_DEPARMENT PRIMARY KEY(DEPARTMENT_ID)
);

CREATE TABLE TBL_ADDRESS(
	ADDRESS_ID VARCHAR(100),
	ADDRESS_POSTAL_CODE NUMBER,
	ADDRESS_LINE1 VARCHAR(100),
	ADDRESS_LINE2 VARCHAR(100),
	CONSTRAINTS PK_ADDRESS PRIMARY KEY(ADDRESS_ID)
);



